import type { NextPage } from "next";
import Head from "next/head";
import { useRouter } from 'next/router'
import Navbar from './components/Navbar'
import Notes from './components/Notes'
import News from './components/News'

const Home: NextPage = () => {
  const router = useRouter()
  const handleClick = () => {
    router.push('/notes')
  }

  return (
    <>
      <Head>
        <title>Batman Dashboard</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <div className="w-screen min-h-screen flex flex-col justify-center items-center p-4 overflow-y-scroll">
        <h2 className="text-[3rem] lg:text-[5rem] md:text-[5rem] font-extrabold text-black-700">
          Bat <span className="text-blue-300">Dash</span>
        </h2>
        <div className="grid grid-cols-1 grid-rows-3 lg:grid-rows-2 md:grid-rows-2 justify-center items-center lg:grid-cols-2 md:grid-cols-2 gap-3 mt-3 pt-3 w-full lg:w-2/3 md:w-full">

          <Notes />

          <News />


          <div className="hover:scale-105 cursor-pointer duration-500 flex flex-col justify-center items-center text-center rounded shadow-xl border-2 border-gray-500 h-full w-full p-6">
            <h2 className="text-lg text-gray-700">Map</h2>
          </div>


          <div className="hover:scale-105 cursor-pointer duration-500 flex flex-col justify-center items-center text-center rounded shadow-xl border-2 border-gray-500 h-full w-full p-6">
            <h2 className="text-lg text-gray-700">Scanner</h2>
          </div>
        </div>
  
      </div>
    </>
  );
};

export default Home;
