import type { NextPage } from "next";
import Head from "next/head";
import { useRouter } from 'next/router'
import Navbar from './components/Navbar'
import Notes from './components/Notes'
import News from './components/news'
import Image from "next/image";
import {RiKeyboardFill } from 'react-icons/ri'
import {CgNotes} from 'react-icons/cg'
import {BiSearch, BiMapAlt} from 'react-icons/bi'


const Home: NextPage = () => {
  const router = useRouter()
  const handleClick = () => {
    router.push('/notes')
  }

  return (
    <>
      <Head>
        <title>Batman Dashboard</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <section id="sidebar">
        <section id="title-container">
          BAT DASH
        </section>
        <section id="links-container">
          <div id="links">
            <div id="icon">
              <RiKeyboardFill />
            </div>
            <span>Dashboard</span>
          </div>
        </section>

        <section id="links-container">
          <div id="links">
            <div id="icon">
              <CgNotes />
            </div>
            <span>Notes</span>
          </div>
        </section>

        <section id="links-container">
          <div id="links">
            <div id="icon">
              <BiMapAlt />
            </div>
            <span>Map</span>
          </div>
        </section>
      </section>
      <section id="main-dashboard-content">
        <section id="top-section">
          <div id='input-box'>
            <input placeholder="Search..."/>
            <BiSearch />
          </div>
        </section>
      </section>
    </>
  );
};

export default Home;
